Checkmarx action
unitecicd/actions pull request #18
Opened 2022-04-01 23:56 UTC by garciacu

Runs Checkmarx scan and analysis

2022-04-02 00:05 UTC, juliocri requested changes

2022-04-02 00:05 UTC, juliocri commented on checkmarx/action.yml
> +        CXSTATUS: '"Verify","Urgent"'
fill these env variables with action inputs, set them as not required and set default value the current value shown right now.

2022-04-04 20:13 UTC, eirascon submitted a review, later dismissed

2022-04-04 22:01 UTC, eirascon approved these changes

2022-04-04 22:14 UTC, juliocri approved these changes

2022-04-04 22:33 UTC, merged