Add virus-scan action
unitecicd/actions pull request #19
Opened 2022-04-02 06:32 UTC by eirascon

Signed-off-by: eirascon <eduardo.i.rascon.garcia@intel.com>

2022-04-02 21:53 UTC, garciacu requested changes

2022-04-02 21:53 UTC, garciacu commented on virus-scan/action.yml
> +    default: scan_results.txt
It's easier if the you build the name of the file here than if it's passed over here maybe user can just pass the name of the repo and you can complete the file name when this action is executed

2022-04-02 21:55 UTC, garciacu requested changes

2022-04-02 21:55 UTC, garciacu commented on virus-scan/action.yml
> +    description: Repository name followed by job name and commit-sha
It's easier if the you build the name of the file here than if it's passed over here maybe user can just pass the name of the repo and you can complete the file name when this action is executed

2022-04-04 23:10 UTC, garciacu approved these changes

2022-04-05 15:13 UTC, garciacu submitted a review, later dismissed

2022-04-05 15:17 UTC, juliocri requested changes

2022-04-05 15:17 UTC, juliocri commented on virus-scan/action.yml
> +    required: true
This input can be optional

2022-04-05 15:17 UTC, juliocri commented on virus-scan/action.yml
> +    required: true
This input can be optional

2022-04-05 15:17 UTC, juliocri commented on virus-scan/action.yml
> +    required: true
This input can be optional

2022-04-05 15:17 UTC, juliocri commented on virus-scan/action.yml
> +          find . -type f -name *."$i" -exec mv '{}' ${{ inputs.scan-directory }}/  \;
The for loop can be avoided if we sen the `input.target` in a format like: `*.{dll,pdb,cs,txt}`

2022-04-05 18:25 UTC, eirascon commented on virus-scan/action.yml
> +          find . -type f -name *."$i" -exec mv '{}' ${{ inputs.scan-directory }}/  \;
I have been working on this but I'm having issues to implement the suggested change.  Do you have an explicit example on how to do this?

2022-04-06 19:38 UTC, garciacu approved these changes

2022-04-06 20:23 UTC, merged